to_do_list/account/urls.py
from django.conf.urls import re_path, include
from account.views import dashboard, register

app_name = 'account'

urlpatterns = [
    # re_path(r"^dashboard/", dashboard, name="dashboard"),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r"^register/", register, name="register"),
]

to_do_list/task_app/urls.py
from django.urls import path

from . import views

app_name = 'task_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('tag/<int:tag_id>/task/create/', views.create_task, name='create_task'),
    path('tag/<int:tag_id>/task/<int:task_id>/edit_status/', views.edit_status_task, name='edit_status_task'),
    path('tag/<int:tag_id>/task/<int:task_id>/send_backlog/', views.send_backlog_task, name='send_backlog_task'),
    path('tag/<int:tag_id>/task/<int:task_id>/block/', views.block_task, name='block_task'),
    path('tag/<int:tag_id>/task/archive_all/', views.archive_all_tasks, name='archive_all_tasks'),
    path('tag/<int:tag_id>/show_all_archived/', views.show_all_archived, name='show_all_archived'),
    path('tag/<int:tag_id>/show_bottom_backlog/', views.show_bottom_backlog, name='show_bottom_backlog'),
    path('tag/<int:tag_id>/task/delete_archived_tasks/', views.delete_archived_tasks, name='delete_archived_tasks'),
    path('task/download_backup/', views.download_backup, name='download_backup'),
    path('tag/<int:tag_id>/create_tag/', views.create_tag, name='create_tag'),
    path('tag/<int:tag_id>/task/import_tasks/', views.import_tasks, name='import_tasks'),
    path('tag/<int:tag_id>/', views.index_tag, name='index_tag'),
]

to_do_list/to_do_list/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('', include('task_app.urls')),
    re_path(r"^", include("account.urls")),
    path('admin/', admin.site.urls),
]

to_do_list/task_app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta

# Create your models here.

class Tag(models.Model):

    name = models.CharField(max_length=300, unique=True)
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        # sets unique values to pair of fields
        unique_together = ('author', 'name',)

    def __str__(self):
        return self.name

class Task(models.Model):
    PRIORITIES = (
        ('1', 'High'),
        ('2', 'Medium'),
        ('3', 'Low'),
    )

    STATUSES = (
        ('b', 'BACKLOG'),
        ('bb', 'BOTTOM BACKLOG'),
        ('wip', 'WIP'),
        ('d', 'DONE'),
        ('a', 'ARCHIVED'),
    )

    description = models.CharField(max_length=300)
    priority = models.CharField(max_length=1, choices=PRIORITIES)
    status = models.CharField(max_length=3, choices=STATUSES, default='b')
    is_blocked = models.BooleanField(default=False)
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    last_working_time = models.DateTimeField(auto_now_add=True)
    spent_time = models.DurationField(
        default = timedelta(days=0)
    )

    tag = models.ManyToManyField(
        Tag,
        related_name='task_tag',
        blank=False
    )

    """
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])
    """
    def __str__(self):
        return self.description

to_do_list/task_app/forms.py
from django import forms
from .models import Task, Tag

class TaskForm(forms.ModelForm):
    description = forms.CharField(
        # this mix business logic with view (templates),
        # but there is no easy way to avoid it.
        widget=forms.TextInput(attrs={
            'type': 'text',
            'class': 'form-control',
            'placeholder': 'Task Name...',
            'aria-label':"Task name",
            'aria-describedby':"button-addon2"
        }),
        label=u'',
        required=True
    )
    priority = forms.ChoiceField(
        # this mix business logic with view (templates),
        # but there is no easy way to avoid it.
        choices=Task.PRIORITIES,
        label=u'Medium',
        required=True,
        widget=forms.Select(attrs={
            'type': 'dropdown-menu',
            'class': 'form-control',
            #'placeholder': 'Task Name...',
            #'aria-label':"Task name",
            #'aria-describedby':"button-addon2"
        }),
    )
    class Meta:
        model = Task
        fields = ('description', 'priority') # priority

class StatusTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('status',)

class TagForm(forms.ModelForm):
    name = forms.CharField(
        # this mix business logic with view (templates),
        # but there is no easy way to avoid it.
        widget=forms.TextInput(attrs={
            'type': 'text',
            'class': 'form-control',
            'placeholder': 'Tag Name...',
            'aria-label':"Tag name",
            'aria-describedby':"button-addon2"
        }),
        label=u'',
        required=True
    )
    class Meta:
        model = Tag
        fields = ('name', )

to_do_list/task_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Task, Tag
from .forms import TaskForm, StatusTaskForm, TagForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.utils import timezone
from django.core import serializers
import datetime
import json

@login_required
def index(request):
    tag = Tag.objects.get_or_create(name='all', author=request.user)[0]
    tag_id = tag.pk
    return redirect('task_app:index_tag', tag_id=tag_id)


@login_required
def index_tag(request, tag_id):
    
    if tag_id is None:
        tag = Tag.objects.get_or_create(name='all', author=request.user)[0]
        tag_id = tag.pk
    else:
        tag = get_object_or_404(Tag, id=tag_id)

    # exclude archived tasks
    task_list = Task.objects\
        .filter(author=request.user)\
        .filter(tag=tag_id)\
        .exclude(status="a")\
        .exclude(status="b")\
        .order_by('priority')

    task_list_backlog = Task.objects\
        .filter(author=request.user)\
        .filter(tag=tag_id)\
        .filter(status='b')\
        .order_by('priority')

    task_form = TaskForm(initial={'priority': '2'})

    tag_list = Tag.objects.filter(author=request.user)

    context = {
        'task_list': task_list,
        'task_list_backlog': task_list_backlog,
        'task_form': task_form,
        'tag_list': tag_list,
        'selected_tag': tag
    }
    return render(request, 'task_app/index.html', context)

"""
@login_required
def create_task(request):
    new_task = None

    if request.method == 'POST':
        # A comment was posted
        new_task = Task.objects.create(
            description=description_data,
        )
        # Create task object but don't save to database yet
        new_task = task_form.save(commit=False)
        # Save the task to the database
        new_task.status = 'wip'
        new_task.save()
        return redirect('task_app:index')
    else:
        task_form = TaskForm()

    context = {
        #'post': post,
        #'comments': comments,
        'new_task': new_task,
        'task_form': task_form
    }

    return render(
        request,
        'task_app/create.html',
        context
    )
"""


@login_required
def edit_status_task(request, tag_id, task_id):
    task = get_object_or_404(Task, id=task_id)

    if tag_id is None:
        tag = Tag.objects.get_or_create(name='all', author=request.user)[0]
        tag_id = tag.pk

    if task.author == request.user:
        if task.status == 'b':
            task.status = 'wip'
            task.last_working_time = timezone.now()
        elif task.status == 'wip':
            working_time = task.spent_time + (timezone.now() - task.last_working_time)
            # round working time deleting microseconds
            task.spent_time = working_time - datetime.timedelta(microseconds=working_time.microseconds)
            task.status = 'd'
        elif task.status == 'd':
            task.status = 'b'
        elif task.status == 'a':
            task.status = 'b'
            task.save()
            return redirect('task_app:show_all_archived', tag_id=tag_id)
        
        task.save()
        return redirect('task_app:index_tag', tag_id=tag_id)
    else:
        return HttpResponse('Unauthorized', status=401)

@login_required
def create_task(request, tag_id):

    new_task = None

    if request.method == 'POST':
        # A comment was posted
        task_form = TaskForm(data=request.POST)
        if task_form.is_valid():
            # Create task object but don't save to database yet
            new_task = task_form.save(commit=False)
            # Save the task to the database
            new_task.status = 'b'
            new_task.author = request.user

            new_task.save()
            tag_all = Tag.objects.get_or_create(name='all', author=request.user)[0]
            if Tag.objects.filter(pk=tag_id).exists():
                tag = (get_object_or_404(Tag, pk=tag_id))
                new_task.tag.add(tag, tag_all)
            else:
                new_task.tag.add(tag_all)

            new_task.save()
            return redirect('task_app:index_tag', tag_id=tag_id)
    else:
        task_form = TaskForm()

    tag = get_object_or_404(Tag, id=tag_id)
    context = {
        #'post': post,
        #'comments': comments,
        'new_task': new_task,
        'task_form': task_form,
        'selected_tag': tag
    }

    return render(
        request,
        'task_app/create.html',
        context
    )

@login_required
def archive_all_tasks(request, tag_id):

    if tag_id is None:
        tag = Tag.objects.get_or_create(name='all', author=request.user)[0]
        tag_id = tag.pk

    task_list = Task.objects\
        .filter(author=request.user)\
        .filter(tag=tag_id)\
        .filter(status='d')
    for task in task_list:
        task.status = 'a'
        task.save()
    
    return redirect('task_app:index_tag', tag_id=tag_id)

@login_required
def delete_archived_tasks(request, tag_id):

    if tag_id is None:
        tag = Tag.objects.get_or_create(name='all', author=request.user)[0]
        tag_id = tag.pk

    task_list = Task.objects\
        .filter(author=request.user)\
        .filter(tag=tag_id)\
        .filter(status='a')
    for task in task_list:
        task.status = 'a'
        task.delete()
    return redirect('task_app:show_all_archived', tag_id=tag_id)

@login_required
def send_backlog_task(request, tag_id, task_id):
    task = get_object_or_404(Task, id=task_id)
    
    if tag_id is None:
        tag = Tag.objects.get_or_create(name='all', author=request.user)[0]
        tag_id = tag.pk

    tag_list = Tag.objects.filter(author=request.user)

    # check if user is allowed to edit tasks
    if task.author == request.user:
        # check if task must be edited
        if task.status not in ('b', 'bb'):
            return HttpResponse('Method not allowed', status=405)
        if task.status == 'bb':
            task.status = 'b'
        elif task.status == 'b':
            task.status = 'bb'
        task.save()
        return redirect('task_app:show_bottom_backlog', tag_id=tag_id)
    else:
        return HttpResponse('Unauthorized', status=401)

@login_required
def show_all_archived(request, tag_id):

    if tag_id is None:
        tag = Tag.objects.get_or_create(name='all', author=request.user)[0]
        tag_id = tag.pk
    else:
        tag = get_object_or_404(Tag, id=tag_id)

    tag_list = Tag.objects.filter(author=request.user)

    task_list = Task.objects\
        .filter(author=request.user)\
        .filter(tag=tag_id)\
        .filter(status='a')\
        .order_by('priority')

    context = {
        'task_list': task_list,
        'tag_list': tag_list,
        'selected_tag': tag
    }
    return render(request, 'task_app/show_all_archived.html', context)

@login_required
def show_bottom_backlog(request, tag_id):

    if tag_id is None:
        tag = Tag.objects.get_or_create(name='all', author=request.user)[0]
        tag_id = tag.pk
    else:
        tag = get_object_or_404(Tag, id=tag_id)

    tag_list = Tag.objects.filter(author=request.user)

    task_list_bottom_backlog = Task.objects\
        .filter(author=request.user)\
        .filter(tag=tag_id)\
        .filter(status='bb')\
        .order_by('priority')
    task_list_backlog = Task.objects\
        .filter(author=request.user)\
        .filter(tag=tag_id)\
        .filter(status='b')\
        .order_by('priority')

    # paginate archived tasks
    page = request.GET.get('page', 1)
    paginator = Paginator(task_list_bottom_backlog, 7)
    try:
        bottom_backlog_tasks = paginator.page(page)
    except PageNotAnInteger:
        bottom_backlog_tasks = paginator.page(1)
    except EmptyPage:
        bottom_backlog_tasks = paginator.page(paginator.num_pages)

    context = {
        'task_list_backlog': task_list_backlog,
        'task_list_bottom_backlog': bottom_backlog_tasks,
        'tag_list': tag_list,
        'selected_tag': tag
    }
    return render(request, 'task_app/list_backlog.html', context)

@login_required
def download_backup(request):
    task_list = Task.objects.filter(author=request.user)

    field_list = (
        'description',
        'priority',
        'status',
        #'author',
        #'last_working_time',
        'spent_time',
        'tag',
    )

    # convert model to text with list of dicts
    task_list_json = serializers.serialize('json', task_list, fields=field_list)

    # extract just fields of dict
    task_list_json = [task['fields'] for task in json.loads(task_list_json)]

    response = HttpResponse(
        json.dumps(task_list_json),
        content_type='application/json'
    )
    response['Content-Disposition'] = 'attachment;'\
        'filename="task_list_{user}_{date_year}{date_month:02d}{date_day:02d}.json"'.format(
        user=request.user,
        date_year=timezone.now().year,
        date_month=timezone.now().month,
        date_day=timezone.now().day
    )

    return response

@login_required
def create_tag(request, tag_id):

    new_tag = None

    if request.method == 'POST':
        tag_form = TagForm(data=request.POST)
        if tag_form.is_valid():
            # Create tag object but don't save to database yet
            new_tag = tag_form.save(commit=False)
            # Save the tag to the database
            new_tag.author = request.user
            new_tag.save()
            return redirect('task_app:index_tag', tag_id=new_tag.pk)
    else:
        tag_form = TagForm()

    tag = get_object_or_404(Tag, id=tag_id)
    context = {
        'new_tag': new_tag,
        'tag_form': tag_form,
        'selected_tag': tag
    }

    return render(
        request,
        'task_app/create_tag.html',
        context
    )

# remove tag
# edit (or add) tag
def import_tasks(request, tag_id):

to_do_list/task_app/templates/task_app/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Matias Duran">
    <title>TO DO</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "task_app/css/bootstrap/bootstrap.min.css" %}" rel="stylesheet">

    <meta name="theme-color" content="#7952b3">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static "task_app/css/cover.css" %}" rel="stylesheet">

  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

    <header class="mb-auto">
      <nav class="navbar navbar-expand-sm navbar-dark " aria-label="Third navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Just a TO DO list</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExample03">
        {% with request.resolver_match.view_name as view_name %}
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
          <li class="nav-item">
            {% if view_name == 'task_app:index_tag' %}
              <a class="nav-link active" aria-current="page" href="{% url "task_app:index_tag" selected_tag.pk %}">TO DO</a>
            {% else %}
              <a class="nav-link" aria-current="page" href="{% url "task_app:index_tag" selected_tag.pk %}">TO DO</a>
            {% endif %}
          </li>
          <li class="nav-item">
            {% if view_name == 'task_app:show_all_archived' %}
              <a class="nav-link active" href="{% url "task_app:show_all_archived" selected_tag.pk %}">Archived</a>
            {% else %}
              <a class="nav-link" href="{% url "task_app:show_all_archived" selected_tag.pk %}">Archived</a>
            {% endif %}
          </li>
          <li class="nav-item">
            {% if view_name == 'task_app:show_bottom_backlog' %}
              <a class="nav-link active" href="{% url "task_app:show_bottom_backlog" selected_tag.pk %}">Backlog</a>
            {% else %}
              <a class="nav-link" href="{% url "task_app:show_bottom_backlog" selected_tag.pk %}">Backlog</a>
            {% endif %}
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown" aria-expanded="false">Tag: {{selected_tag.name}}</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown03">
                <li><a class="dropdown-item" href="{% url "task_app:create_tag" selected_tag.pk %}">+ Create Tag...</a></li>
                {% for tag_item in tag_list %}
                  <li><a class="dropdown-item" href="{% url "task_app:index_tag" tag_item.pk %}">{{tag_item}}</a></li>
                {% endfor %}
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "account:logout" %}">Logout</a>
          </li>
        </ul>
        {% endwith %}
      </div>
    </div>
  </nav>
    </header>

    <main class="px-3">      
      <div id="content">
          {% block content %}{% endblock %}
      </div>

    </main>

    <footer class="mt-auto text-white-50"> 
        <a class="text-white" href="{% url "task_app:archive_all_tasks" selected_tag.pk %}">Archive all tasks</a> |
        <a class="text-white" href="{% url "task_app:delete_archived_tasks" selected_tag.pk %}">Delete all archived tasks</a> |
        <a class="text-white" href="{% url "task_app:import_tasks" selected_tag.pk %}">Import / Export tasks</a>
      <!--
      <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
      -->
    </footer>
  </div>


    <script src="{% static "task_app/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
  </body>
</html>

to_do_list/task_app/templates/task_app/create.html
{% extends "task_app/base.html" %}
{% block title %}Adding tasks{% endblock %}
{% block content %}

    {% if new_task %}
        <h2>Your task has been added.</h2>
    {% else %}
        <form method="post">
        <div class="input-group mb-3">
        {{ task_form }} {% comment %} task_form.as_p {% endcomment%}
        {% csrf_token %}
        <!--<p><input type="submit" value="Add task"></p> -->
        <button class="btn btn-outline-secondary" type="submit" id="description_data">Add Task</button>
        </div>
        </form>
    {% endif %}

{% endblock %}

to_do_list/task_app/templates/task_app/create_tag.html
{% extends "task_app/base.html" %}
{% block title %}Add a tag{% endblock %}
{% block content %}

    {% if new_tag %}
        <h2>Your Tag (Project) has been added.</h2>
    {% else %}
        <form method="post">
            <div class="input-group mb-3">
            {{ tag_form.name }}
            {% csrf_token %}
            <button class="btn btn-outline-secondary" type="submit" id="tag_data">Add Tag (Project)</button>
            </div>
        </form>
    {% endif %}

{% endblock %}

to_do_list/task_app/templates/task_app/edit.html
{% extends "task_app/base.html" %}
{% block title %}Edit tasks{% endblock %}
{% block content %}

        <h2>Edit task: {{task}}</h2>
        <form method="post">
        {{ task_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Edit task"></p>
        </form>

{% endblock %}

to_do_list/task_app/templates/task_app/import_tasks.html
{% extends "task_app/base.html" %}
{% block title %}Import tasks{% endblock %}
{% block content %}
    
    {% if success %}
        <h2>Success!!</h2>
    {% endif %}

    <form action="{% url "task_app:import_tasks" selected_tag.pk %}" method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}
    <div class="input-group mb-3">
        
        <div class="col-md-12">
            <label for="batch_file" class="form-label"><span class="text-start">Import Tasks</span></label>
            <input type="file" name="batch_file" id="batch_file" required="True" class="form-control" placeholder="Import a JSON file...">
        </div>

        <div class="col-md-12">
            ---
        </div>

        <div class="col-md-12">
            <button class="btn btn-outline-secondary" type="submit">Upload File</button>
        </div>

    </div>
    </form>

    ---

    <p>
        <a class="text-white" href="{% url "task_app:download_backup" %}">Export Tasks</a>
    </p>

{% endblock %}

to_do_list/task_app/templates/task_app/index.html
{% extends "task_app/base.html" %}
{% block content %}
    {% for task in task_list %}
    <p class="lead">
        {% if task.status == 'wip' %}
            [*] {{ task.id }}. <a class="text-white text-decoration-none fw-bold"
                href="{% url "task_app:edit_status_task" selected_tag.pk task.id %}">{{task}} [{{task.get_status_display}}]</a>
        {% elif task.status == 'd' or task.status == 'a' %}
            [+] {{ task.id }}. <a class="text-decoration-none text-white text-decoration-line-through"
                href="{% url "task_app:edit_status_task" selected_tag.pk task.id %}">{{task}}</a> [{{task.get_status_display}}] ({{task.spent_time}})
        {% endif %}
    </p>
    {% endfor %}
    ---
    {% for task in task_list_backlog %}
        {% if task.is_blocked %}
        <p class="lead text-danger font-weight-bold"><b>[X] </b> <a class="text-danger font-weight-bold text-decoration-none"
            href="#">{{task}}!!</a>
        {% else %}
        <p class="lead">[-] {{ task.id }}. <a class="text-white text-decoration-none"
            href="{% url "task_app:edit_status_task" selected_tag.pk task.id %}" selected_tag.pk task.id %}">{{task}}</a>
        {% endif %}
            <button onclick="document.location='{% url "task_app:block_task" selected_tag.pk task.id %}'" class="btn btn-outline-secondary btn-small">block!</button>
    </p> 
    {% endfor %}

    <br>

    {% if task_form %}

    <form action="{% url "task_app:create_task" selected_tag.pk %}" method="post">
        <div class="input-group mb-3">
            {{ task_form.description }}
            <div class="mw-10">
            {{ task_form.priority }}
            </div>
            {% csrf_token %}
            <button class="btn btn-outline-secondary" type="submit" id="description_data">Add Task</button>
        </div>
    </form>

    {% endif %}



    {% comment %}
    <a class="btn btn-lg btn-secondary fw-bold border-white bg-white"
                href="{% url "task_app:edit_status_task" task.id %}">{{task}} ({{ task.id }})</a>
    <ul>
        {% for task in task_list %}

        <li>
            {% if task.status == 'wip' %}
                <a href="{% url "task_app:edit_status_task" task.id %}">{{task}}</a>
            {% else %}
                <del><a href="{% url "task_app:edit_status_task" task.id %}">{{task}}</a></del>
            {% endif %} ({{ task.id }})
        </li>

        {% endfor %}
    </ul>
    {% endcomment %}
{% endblock %}

<!--
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
-->

<!-- <p>TEXTO: {{texto}}</p> -->

to_do_list/task_app/templates/task_app/list_backlog.html
{% extends "task_app/base.html" %}
{% block content %}
    {% for task in task_list_backlog %}
    <p class="lead">
        [-] {{ task.id }}. <a class="text-white text-decoration-none"
            href="{% url "task_app:send_backlog_task" selected_tag.pk task.id %}">{{task}}</a>
    </p> 
    {% endfor %}

    ---

    {% for task in task_list_bottom_backlog %}
    <p class="lead">
        [ ] {{ task.id }}. <a class="text-white text-decoration-none"
            href="{% url "task_app:send_backlog_task" selected_tag.pk task.id %}">{{task}}</a>
    </p> 
    {% endfor %}

    {% if task_list_bottom_backlog.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% if task_list_bottom_backlog.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ task_list_bottom_backlog.previous_page_number }}">Previous</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">Previous</a></li>
        {% endif %}
        {% for i in task_list_bottom_backlog.paginator.page_range %}
            {% if task_list_bottom_backlog.number == i %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if task_list_bottom_backlog.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ task_list_bottom_backlog.next_page_number }}">Next</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">Next</a></li>
        {% endif %}
    </ul>
    {% endif %}

{% endblock %}

to_do_list/task_app/templates/task_app/show_all_archived.html
{% extends "task_app/base.html" %}
{% block content %}
    {% for task in task_list %}
    <p class="lead">
        {% if task.status == 'wip' %}
            [*] {{ task.id }}. <a class="text-white text-decoration-none fw-bold"
                href="{% url "task_app:edit_status_task" selected_tag.pk task.id %}">{{task}} [{{task.get_status_display}}]</a>
        {% elif task.status == 'd' or task.status == 'a' %}
            [+] {{ task.id }}. <a class="text-decoration-none text-white text-decoration-line-through"
                href="{% url "task_app:edit_status_task" selected_tag.pk task.id %}">{{task}}</a> [{{task.get_status_display}}] ({{task.spent_time}})
        {% endif %}
    </p>
    {% endfor %}
    ---
    {% for task in task_list_backlog %}
    <p class="lead">
        [-] {{ task.id }}. <a class="text-white text-decoration-none"
            href="{% url "task_app:edit_status_task" selected_tag.pk task.id %}">{{task}}</a>
    </p> 
    {% endfor %}




    {% comment %}
    <a class="btn btn-lg btn-secondary fw-bold border-white bg-white"
                href="{% url "task_app:edit_status_task" task.id %}">{{task}} ({{ task.id }})</a>
    <ul>
        {% for task in task_list %}

        <li>
            {% if task.status == 'wip' %}
                <a href="{% url "task_app:edit_status_task" task.id %}">{{task}}</a>
            {% else %}
                <del><a href="{% url "task_app:edit_status_task" task.id %}">{{task}}</a></del>
            {% endif %} ({{ task.id }})
        </li>

        {% endfor %}
    </ul>
    {% endcomment %}
{% endblock %}

<!--
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
-->

<!-- <p>TEXTO: {{texto}}</p> -->